from enum import Enum, auto
from dataclasses import dataclass


class RequestMethods(Enum):
    GET = auto()
    HEAD = auto()
    POST = auto()
    PUT = auto()
    DELETE = auto()
    OPTIONS = auto()
    PATCH = auto()


class Area(Enum):
    PATENTES = 1
    MARCAS = 2
    PROTECCION_A_LA_PROPIEDAD_INTELECTUAL = 3
    AREA_7 = 7 # FIXME: set Area 7
    AREA_8 = 8 # FIXME: set Area 8


class Gaceta(Enum):
    def __init__(self, id_gaceta: int, area: Area):
            self.id_gaceta = id_gaceta
            self.area = area

    SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES          = (2, Area.PATENTES)
    PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES                          = (3, Area.PATENTES)
    LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS                        = (10, Area.PATENTES)
    PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI     = (17, Area.PATENTES)
    REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS       = (24, Area.PATENTES)
    INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE                                    = (29, Area.PATENTES)
    PATENTES_VIGENTES_QUE_INCUMPLEN_LO_DISPUESTO_EN_EL_ART_162_LFPPI                             = (39, Area.PATENTES)
    NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES                                        = (41, Area.PATENTES)
    RENOVACIONES_DE_DISENOS_INDUSTRIALES                                                         = (42, Area.PATENTES)
    MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES                                              = (1, Area.MARCAS)
    SOLICITUDES_DE_MARCAS_NOMBRES_COMERCIALES_Y_AVISOS_COMERCIALES_ABANDONADAS                   = (18, Area.MARCAS)
    OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS                                                      = (30, Area.MARCAS)
    SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO             = (35, Area.MARCAS)
    OPOSICION_A_SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES                               = (36, Area.MARCAS)
    CONSERVACION_DE_LOS_DERECHOS                                                                 = (37, Area.MARCAS)
    NOTIFICACION_DE_RESOLUCIONES_REQUERIMIENTOS_Y_DEMAS_ACTOS                                    = (40, Area.MARCAS)
    SIGNOS_DISTINTIVOS_CADUCOS                                                                   = (81, Area.MARCAS)
    PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE                              = (4, Area.PROTECCION_A_LA_PROPIEDAD_INTELECTUAL)
    PUBLICACION_DE_ACUERDOS_DIARIAMENTE                                                          = (43, Area.PROTECCION_A_LA_PROPIEDAD_INTELECTUAL)
    INVENCIONES_Y_MARCAS                                                                         = (13, Area.AREA_7)
    MARCAS_EXTINGUIDAS                                                                           = (25, Area.AREA_7)
    JURIDICO                                                                                     = (9, Area.AREA_8)
    CLASIFICACION_INTERNACIONAL_DE_PRODUCTOS_Y_SERVICIOS_PARA_EL_REGISTRO_DE_LAS_MARCAS          = (27, Area.AREA_8)
    LISTA_COMPLEMENTARIA_A_LA_CLASIFICACION_INTERNACIONAL_DE_PRODUCTOS_Y_SERVICIOS               = (28, Area.AREA_8)
    CLASIFICACION_INTERNACIONAL_DE_PRODUCTOS_Y_SERVICIOS_PARA_EL_REGISTRO_DE_LAS_MARCAS_PARTE_I  = (32, Area.AREA_8)
    CLASIFICACION_INTERNACIONAL_DE_PRODUCTOS_Y_SERVICIOS_PARA_EL_REGISTRO_DE_LAS_MARCAS_PARTE_II = (34, Area.AREA_8)


# class Seccion(Enum):
#     def __init__(self, id_seccion: int, gaceta: Gaceta):
#         self.id_seccion = id_seccion
#         self.gaceta = gaceta

#     SOLICITUDES_DE_MARCAS                   = (100188, Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)
#     SOLICITUDES_DE_AVISOS_COMERCIALES       = (100190, Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)
#     SOLICITUDES_DE_NOMBRES_COMERCIALES      = (100192, Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)


@dataclass(frozen=True)
class Seccion():
    id_seccion: int
    name: str
    gaceta: Gaceta


MARCAS_REGISTRADAS = Seccion(2, "Marcas Registradas", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
AVISOS_COMERCIALES_REGISTRADOS = Seccion(52, "Avisos Comerciales Registrados", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
NOMBRES_COMERCIALES_PUBLICADOS = Seccion(102, "Nombres Comerciales Publicados", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_MARCAS_REGISTRADAS_GACETA_DE_JULIO_DEL_2016 = Seccion(602, "Fe de Erratas de Marcas Registradas (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_MARCAS_GACETA_DE_JULIO_DEL_2016 = Seccion(609, "Fe de Erratas de Limitación de Productos Favorables de Marcas (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_AVISOS_COMERCIALES_REGISTRADOS_EN_EL_MES_GACETA_DE_JULIO_DEL_2016 = Seccion(100205, "Fe de Erratas de Avisos Comerciales Registrados en el Mes (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_RENOVACION_GACETA_DE_JULIO_DEL_2016 = Seccion(100207, "Fe de Erratas de Renovación (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_INSCRIPCION_DE_LIMITACION_GACETA_DE_JULIO_DEL_2016 = Seccion(100208, "Fe de Erratas de Inscripción de Limitación (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
FE_DE_ERRATAS_DE_INSCRIPCION_DE_CANCELACION_PARCIAL_GACETA_DE_JULIO_DEL_2016 = Seccion(100209, "Fe de Erratas de Inscripción de Cancelación Parcial (Gaceta de Julio del 2016)", Gaceta.MARCAS_REGISTRADAS_AVISOS_Y_NOMBRES_COMERCIALES)
SOLICITUDES_DE_PATENTE = Seccion(252, "Solicitudes de Patente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_PATENTE_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES = Seccion(253, "Solicitudes de Patente conforme al Tratado de Cooperación en Materia de Patentes", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_PATENTE_PUBLICADAS_ANTICIPADAMENTE = Seccion(254, "Solicitudes de Patente publicadas anticipadamente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES_PUBLICADAS_ANTICIPADAMENTE = Seccion(255, "Solicitudes conforme al Tratado de Cooperación en Materia de Patentes publicadas anticipadamente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_QUE_SE_TRANSFORMARON_DE_REGISTROS_A_SOLICITUDES_DE_PATENTES = Seccion(259, "Solicitudes que se transformaron de registros a solicitudes de patentes", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DE_PATENTE = Seccion(261, "Fe de Erratas de Solicitudes de Patente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DE_PATENTE_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES = Seccion(262, "Fe de Erratas de Solicitudes de Patente conforme al Tratado de Cooperación en Materia de Patentes", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_NORMALES_PUBLICADAS_ANTICIPADAMENTE = Seccion(263, "Fe de Erratas de Solicitudes normales publicadas anticipadamente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DIVISIONALES_DE_PATENTE = Seccion(100235, "Solicitudes Divisionales de Patente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD = Seccion(100237, "Solicitudes de Registro de Modelo de Utilidad", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES = Seccion(100238, "Solicitudes de Registro de Modelo de Utilidad conforme al Tratado de Cooperación en Materia de Patentes", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DIVISIONALES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD = Seccion(100239, "Solicitudes Divisionales de Registro de Modelo de Utilidad", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD = Seccion(100240, "Fe de Erratas de Solicitudes de Registro de Modelo de Utilidad", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL = Seccion(100244, "Solicitudes de Registro de Diseño Industrial", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_DIVISIONALES = Seccion(100245, "Solicitudes de Registro de Diseño Industrial Divisionales", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DISENO_INDUSTRIAL = Seccion(100246, "Fe de Erratas de Solicitudes de Registro Diseño Industrial", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_CONFORME_AL_SISTEMA_DE_LA_HAYA = Seccion(100522, "Solicitudes de Registro de Diseño Industrial conforme al Sistema de la Haya", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
SOLICITUDES_DIVISIONALES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_CONFORME_AL_SISTEMA_DE_LA_HAYA = Seccion(100582, "Solicitudes Divisionales de Registro de Diseño Industrial conforme al Sistema de la Haya", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DIVISIONALES_DE_PATENTE = Seccion(100880, "Fe de Erratas de Solicitudes Divisionales de Patente", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_DIVISIONALES = Seccion(100882, "Fe de Erratas de Solicitudes de Registro de Diseño Industrial Divisionales", Gaceta.SOLICITUDES_DE_PATENTE_DE_REGISTROS_DE_MODELO_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_302 = Seccion(302, "Patentes", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
REGISTROS_DE_MODELOS_DE_UTILIDAD_304 = Seccion(304, "Registros de Modelos de Utilidad", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES_305 = Seccion(305, "Registros de Diseños Industriales: Modelos y Dibujos Industriales ", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
ESQUEMAS_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS = Seccion(312, "Esquemas de Trazado de Circuitos Integrados", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_PATENTES = Seccion(332, "Fe de Erratas de Patentes", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_REGISTROS_DE_MODELOS_DE_UTILIDAD = Seccion(333, "Fe de Erratas de Registros de Modelos de Utilidad", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES = Seccion(334, "Fe de Erratas de Registros de Diseños Industriales: Modelos y Dibujos Industriales", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
FE_DE_ERRATAS_DE_LICENCIAS = Seccion(335, "Fe de Erratas de Licencias", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
REGISTROS_DE_MODELO = Seccion(1420, "Registros de Modelo", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
CERTIFICADOS_DE_INVENCION = Seccion(1421, "Certificados de Invención", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
EMBARGOS_JUDICIALES_RELACIONADOS_CON_PATENTES = Seccion(1573, "Embargos judiciales relacionados con patentes", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_QUE_CUMPLIERON_SU_PLAZO_DE_VIGENCIA = Seccion(1574, "Patentes que cumplieron su plazo de vigencia", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
ADHESION_DE_GOBIERNOS_A_LA_CONVENCION_DE_UNION_DE_PARIS = Seccion(1575, "Adhesión de gobiernos a la Convención de Unión de París", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
ADJUDICACION_DE_PATENTES_OTORGADAS = Seccion(1576, "Adjudicación de patentes otorgadas", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_CUYA_FALTA_DE_EXPLOTACION_SE_HA_COMPROBADO = Seccion(1577, "Patentes cuya falta de explotación se ha comprobado", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
RESOLUCIONES_DE_PRIORIDAD_RELACIONADAS_CON_PATENTES_CONCEDIDAS = Seccion(1578, "Resoluciones de prioridad relacionadas con patentes concedidas", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
RECTIFICACIONES = Seccion(1579, "Rectificaciones", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
INVENCIONES_CUYA_NOVEDAD_FUE_EXAMINADA = Seccion(1580, "Invenciones cuya novedad fue examinada", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
HIPOTECAS_SOBRE_DERECHOS_DE_PATENTES_CONCEDIDAS = Seccion(1581, "Hipotecas sobre derechos de patentes concedidas", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_CUYA_PRIORIDAD_DE_FECHA_LEGAL_HA_SIDO_RECONOCIDA_EN_MEXICO = Seccion(1582, "Patentes cuya prioridad de fecha legal ha sido reconocida en México", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_CUYOS_DERECHOS_DEL_SEGUNDO_PLAZO_FUERON_PAGADOS = Seccion(1583, "Patentes cuyos derechos del segundo plazo fueron pagados", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
AVISOS_BIMESTRALES_EN_RELACION_CON_LA_EXPLOTACION_INDUSTRIAL_DE_PATENTES = Seccion(1584, "Avisos Bimestrales en relación con la Explotación Industrial de Patentes", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_QUE_HAN_SIDO_CONVERTIDAS_EN_DEFINITIVAS = Seccion(1585, "Patentes que han sido convertidas en definitivas", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
PATENTES_PROVISIONALES_QUE_HAN_CADUCADO_POR_NO_HABER_PAGADO_EL_IMPUESTO_DEL_SEGUNDO_PLAZO = Seccion(1586, "Patentes provisionales que han caducado por no haber pagado el impuesto del segundo plazo", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
ASUNTOS_ABANDONADOS_Y_DESECHADOS = Seccion(1587, "Asuntos abandonados y desechados", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES_100267 = Seccion(100267, "Registros de Diseños Industriales: Modelos y Dibujos Industriales", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
REGISTROS_DE_DISENOS_INDUSTRIALES_CONFORME_AL_ARREGLO_DE_LA_HAYA_MODELOS_Y_DIBUJOS_INDUSTRIALES = Seccion(100720, "Registros de Diseños Industriales conforme al Arreglo de la Haya: Modelos y Dibujos Industriales", Gaceta.PATENTES_REGISTROS_DE_MODELOS_DE_UTILIDAD_Y_DE_DISENOS_INDUSTRIALES)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PROCESOS_DE_PROPIEDAD_INDUSTRIAL_152 = Seccion(152, "Emitidas por la Subdirección Divisional de Procesos de Propiedad Industrial", Gaceta.PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_CUMPLIMIENTO_DE_EJECUTORIA_153 = Seccion(153, "Emitidas por la Subdirección Divisional de Cumplimiento de Ejecutoria", Gaceta.PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_INFRACCIONES_ADMINISTRATIVAS_EN_MATERIA_DE_COMERCIO_154 = Seccion(154, "Emitidas por la Subdirección Divisional de Infracciones Administrativas en Materia de Comercio", Gaceta.PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PREVENCION_DE_LA_COMPETENCIA_DESLEAL_155 = Seccion(155, "Emitidas por la Subdirección Divisional de Prevención de la Competencia Desleal", Gaceta.PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE)
RECURSOS_DE_REVISION_157 = Seccion(157, "Recursos de Revisión", Gaceta.PUBLICACION_DE_RESOLUCIONES_ANEXOS_Y_FE_DE_ERRATAS_MENSUALMENTE)
TRANSMISION_DE_DERECHOS = Seccion(307, "Transmisión de Derechos", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
LICENCIAS_DE_EXPLOTACION = Seccion(308, "Licencias de Explotación", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
SUBLICENCIAS_DE_EXPLOTACION = Seccion(309, "Sublicencias de Explotación", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
TRANSFORMACION_DE_REGIMEN_JURIDICO = Seccion(310, "Transformación de Régimen Jurídico", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
CAMBIO_DE_RAZON_SOCIAL = Seccion(311, "Cambio de Razón Social", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
CAMBIOS_EN_PATENTES = Seccion(315, "Cambios en Patentes", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
CAMBIOS_DE_REGISTROS_DE_DISENOS_INDUSTRIALES = Seccion(316, "Cambios de Registros de Diseños Industriales", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
CAMBIOS_DE_REGISTROS_DE_MODELO_DE_UTILIDAD = Seccion(317, "Cambios de Registros de Modelo de Utilidad", Gaceta.LICENCIAS_TRANSMISIONES_Y_CAMBIOS_EN_SOLICITUDES_PATENTES_Y_REGISTROS)
PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS = Seccion(3004, "Patentes vigentes susceptibles de ser empleadas en medicamentos alopáticos", Gaceta.PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI)
FE_DE_ERRATAS_100266 = Seccion(100266, "Fe de Erratas", Gaceta.PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI)
LISTADO_DE_MEDICAMENTOS_VIGENTES = Seccion(100621, "Listado de Medicamentos Vigentes", Gaceta.PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI)
PRIMERA_SECCION_FARMACOQUIMICOS = Seccion(100964, "Primera Sección: Farmacoquímicos", Gaceta.PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI)
SEGUNDA_SECCION_BIOTECNOLOGICOS = Seccion(100965, "Segunda Sección: Biotecnológicos", Gaceta.PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS_ART_162_LFPPI)
SOLICITUDES_DE_MARCAS_ABANDONADAS = Seccion(2005, "Solicitudes de Marcas Abandonadas", Gaceta.SOLICITUDES_DE_MARCAS_NOMBRES_COMERCIALES_Y_AVISOS_COMERCIALES_ABANDONADAS)
SOLICITUDES_DE_NOMBRES_COMERCIALES_ABANDONADAS = Seccion(2006, "Solicitudes de Nombres Comerciales Abandonadas", Gaceta.SOLICITUDES_DE_MARCAS_NOMBRES_COMERCIALES_Y_AVISOS_COMERCIALES_ABANDONADAS)
SOLICITUDES_DE_AVISOS_COMERCIALES_ABANDONADAS = Seccion(2007, "Solicitudes de Avisos Comerciales Abandonadas", Gaceta.SOLICITUDES_DE_MARCAS_NOMBRES_COMERCIALES_Y_AVISOS_COMERCIALES_ABANDONADAS)
OFICIOS_REFERENTES_A_SOLICITUDES_DE_PATENTE = Seccion(4001, "Oficios referentes a solicitudes de patente", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
OFICIOS_REFERENTES_A_SOLICITUDES_DE_DISENOS_INDUSTRIALES_O_MODELOS_DE_UTILIDAD = Seccion(4002, "Oficios referentes a solicitudes de diseños industriales o modelos de utilidad", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_PATENTE_ABANDONADAS_POR_FALTA_DE_PAGO_PARA_EXPEDICION_DE_TITULO = Seccion(4101, "Solicitudes de patente abandonadas por falta de pago para expedición de título", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_MODELOS_DE_UTILIDAD_ABANDONADAS_Y_DESISTIDAS = Seccion(4102, "Solicitudes de modelos de utilidad abandonadas y desistidas", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_DISENOS_INDUSTRIALES_ABANDONADAS_Y_DESISTIDAS = Seccion(4103, "Solicitudes de diseños industriales abandonadas y desistidas", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
CERTIFICADOS_DE_INVENCION_REGISTRADOS_DECLARADOS_CADUCOS_POR_TERMINO_DE_TIEMPO_DE_VIGENCIA = Seccion(4104, "Certificados de invención registrados declarados caducos por término de tiempo de vigencia", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_PATENTE_ABANDONADAS = Seccion(4105, "Solicitudes de patente abandonadas", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
PATENTES_DECLARADAS_CADUCAS_POR_TERMINO_DE_SUS_PLAZOS_DE_VIGENCIA = Seccion(4106, "Patentes declaradas caducas por término de sus plazos de vigencia", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
REGISTROS_DE_MODELO_Y_DIBUJOS_INDUSTRIALES_QUE_CADUCARON = Seccion(4107, "Registros de modelo y dibujos industriales que caducaron", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_CERTIFICADOS_DE_INVENCION_ABANDONADOS = Seccion(4108, "Solicitudes de Certificados de Invención abandonados", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_REGISTROS_DE_MODELO_ABANDONADOS = Seccion(4109, "Solicitudes de Registros de Modelo abandonados", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
CITA_A_PAGO_DE_SOLICITUDES_DE_PATENTES = Seccion(11610, "Cita a pago de Solicitudes de Patentes", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
CITA_A_PAGO_DE_SOLICITUDES_DE_MODELOS_DE_UTILIDAD = Seccion(11615, "Cita a pago de Solicitudes de Modelos de Utilidad", Gaceta.REQUISITOS_DE_EXAMEN_DE_FORMA_Y_FONDO_ABANDONOS_DE_SOLICITUDES_DE_PATENTES_Y_REGISTROS)
SOLICITUDES_DE_USO_LIBRE_ABANDONADAS_DESISTIDAS_DESECHADAS_RETIRADAS_O_NEGADA_SU_CONCESION = Seccion(10001, "Solicitudes de uso libre: abandonadas, desistidas, desechadas, retiradas o negada su concesión", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
SOLICITUDES_DE_PATENTE_INTERNACIONALES_CUYA_FASE_NACIONAL_SE_ABANDONO_DESISTIO_DESECHO_O_RETIRO = Seccion(10002, "Solicitudes de patente internacionales, cuya fase nacional se abandonó, desistió, desechó o retiró", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
PATENTES_CADUCAS_POR_TERMINO_DE_VIGENCIA = Seccion(10003, "Patentes caducas por término de vigencia", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
PATENTES_CADUCAS_POR_FALTA_DE_PAGO = Seccion(10004, "Patentes caducas por falta de pago", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_MODELO_DE_UTILIDAD_CADUCOS_POR_TERMINO_DE_VIGENCIA = Seccion(10006, "Registros de modelo de utilidad caducos por término de vigencia", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_MODELO_DE_UTILIDAD_CADUCOS_POR_FALTA_DE_PAGO = Seccion(10007, "Registros de modelo de utilidad caducos por falta de pago", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_DISENO_INDUSTRIAL_CADUCOS_POR_TERMINO_DE_VIGENCIA = Seccion(10008, "Registros de diseño industrial caducos por término de vigencia", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_DISENO_INDUSTRIAL_CADUCOS_POR_FALTA_DE_PAGO = Seccion(10009, "Registros de diseño industrial caducos por falta de pago", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_ESQUEMA_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS_CADUCOS_POR_TERMINO_DE_VIGENCIA = Seccion(10010, "Registros de esquema de trazado de circuitos integrados caducos por término de vigencia", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
REGISTROS_DE_ESQUEMA_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS_CADUCOS_POR_FALTA_DE_PAGO = Seccion(10011, "Registros de esquema de trazado de circuitos integrados caducos por falta de pago", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
FE_DE_ERRATAS_10030 = Seccion(10030, "Fe de Erratas", Gaceta.INVENCIONES_DE_DOMINIO_PUBLICO_Y_SOLICITUDES_DE_USO_LIBRE)
SOLICITUDES_DE_MARCAS_11010 = Seccion(11010, "Solicitudes de Marcas", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_NOMBRES_COMERCIALES_11020 = Seccion(11020, "Solicitudes de Nombres Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_AVISOS_COMERCIALES_11030 = Seccion(11030, "Solicitudes de Avisos Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
REGISTROS_DE_MARCAS = Seccion(11040, "Registros de Marcas", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
ORDENES_DE_PUBLICACION_DE_NOMBRES_COMERCIALES = Seccion(11050, "Órdenes de publicación de Nombres Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
REGISTROS_DE_AVISOS_COMERCIALES = Seccion(11060, "Registros de Avisos Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_MARCAS_100177 = Seccion(100177, "Solicitudes de Marcas", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_NOMBRES_COMERCIALES_100179 = Seccion(100179, "Solicitudes de Nombres Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_AVISOS_COMERCIALES_100181 = Seccion(100181, "Solicitudes de Avisos Comerciales", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_INSCRIPCION_DE_LICENCIA_DE_USO_O_FRANQUICIA = Seccion(100183, "Solicitudes de Inscripción de Licencia de Uso o Franquicia", Gaceta.OFICIOS_REFERENTES_A_SIGNOS_DISTINTIVOS)
SOLICITUDES_DE_MARCAS_100188 = Seccion(100188, "Solicitudes de Marcas", Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)
SOLICITUDES_DE_AVISOS_COMERCIALES_100190 = Seccion(100190, "Solicitudes de Avisos Comerciales", Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)
SOLICITUDES_DE_NOMBRES_COMERCIALES_100192 = Seccion(100192, "Solicitudes de Nombres Comerciales", Gaceta.SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES_PRESENTADAS_ANTE_EL_INSTITUTO)
ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_AVISOS_COMERCIALES = Seccion(100198, "Escritos de Oposiciones a Solicitudes de Avisos Comerciales ", Gaceta.OPOSICION_A_SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES)
ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_MARCAS = Seccion(100199, "Escritos de Oposiciones a Solicitudes de Marcas", Gaceta.OPOSICION_A_SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES)
ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_NOMBRES_COMERCIALES = Seccion(100200, "Escritos de Oposiciones a Solicitudes de Nombres Comerciales", Gaceta.OPOSICION_A_SOLICITUDES_DE_MARCAS_AVISOS_Y_NOMBRES_COMERCIALES)
MARCAS_RENOVADAS_EN_EL_MES = Seccion(3, "Marcas Renovadas en el Mes", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
PERMISO_DE_USO_AUTORIZADO_DE_MARCAS = Seccion(4, "Permiso de Uso Autorizado de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
TRANSMISIONES_O_ENAJENACIONES_DE_DERECHOS_DE_MARCAS = Seccion(5, "Transmisiones o Enajenaciones de Derechos de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_MARCAS = Seccion(6, "Cambios de Nombre Jurídico de Titulares de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_MARCAS = Seccion(7, "Cambios de Régimen Jurídico de Titulares de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_MARCAS = Seccion(8, "Cancelación Voluntaria de Registros de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_MARCAS = Seccion(9, "Limitación de Productos Favorables de Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_UBICACION_DE_FABRICAS_O_ESTABLECIMIENTOS_RELACIONADOS_CON_MARCAS = Seccion(12, "Cambios de Ubicación de Fabricas o Establecimientos Relacionados con Marcas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
NUEVA_UBICACION_DE_FABRICAS_SUBSIDIARIAS = Seccion(13, "Nueva Ubicacion de Fabricas Subsidiarias", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_CAMBIO_EN_EL_NOMBRE_DEL_TITULAR = Seccion(26, "Inscripción de Cambio en el Nombre del Titular", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_UN_CAMBIO_EN_LA_TITULARIDAD_TOTAL = Seccion(27, "Inscripción de un Cambio en la Titularidad Total", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_UN_CAMBIO_EN_LA_TITULARIDAD_PARCIAL = Seccion(28, "Inscripción de un Cambio en la Titularidad Parcial", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
RENOVACION = Seccion(29, "Renovación", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_LIMITACION = Seccion(30, "Inscripción de Limitación", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_CANCELACION_TOTAL = Seccion(31, "Inscripción de Cancelación Total", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
INSCRIPCION_DE_CANCELACION_PARCIAL = Seccion(32, "Inscripción de Cancelación Parcial", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
RENUNCIA_REGISTROS_INTERNACIONALES = Seccion(35, "Renuncia Registros Internacionales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AVISOS_COMERCIALES_RENOVADOS_EN_EL_MES = Seccion(53, "Avisos Comerciales Renovados en el Mes", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
PERMISO_DE_USO_AUTORIZADO_DE_AVISOS_COMERCIALES = Seccion(54, "Permiso de Uso Autorizado de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
TRANSMISIONES_O_ENAJENACIONES_DE_AVISOS_COMERCIALES = Seccion(55, "Transmisiones o Enajenaciones de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_AVISOS_COMERCIALES = Seccion(56, "Cambios de Nombre Jurídico de Titulares de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_AVISOS_COMERCIALES = Seccion(57, "Cambios de Régimen Jurídico de Titulares de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_AVISOS_COMERCIALES = Seccion(58, "Cancelación Voluntaria de Registros de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_AVISOS_COMERCIALES = Seccion(59, "Limitación de Productos Favorables de Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_ESTABLECIMIENTOS_RELACIONADOS_CON_AVISOS_COMERCIALES = Seccion(62, "Cambios de Establecimientos Relacionados con Avisos Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
NOMBRES_COMERCIALES_RENOVADOS_EN_EL_MES = Seccion(103, "Nombres Comerciales Renovados en el Mes", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
PERMISO_DE_USO_AUTORIZADO_DE_NOMBRES_COMERCIALES = Seccion(104, "Permiso de Uso Autorizado de Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
TRANSMISIONES_O_ENAJENACIONES_DE_NOMBRES_COMERCIALES = Seccion(105, "Transmisiones o Enajenaciones de Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_NOMBRES_COMERCIALES = Seccion(106, "Cambios de Nombre Jurídico de Titulares de Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_NOMBRES_COMERCIALES = Seccion(107, "Cambios de Régimen Jurídico de Titulares de Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_NOMBRES_COMERCIALES = Seccion(108, "Cancelación Voluntaria de Registros de Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
CAMBIOS_DE_ESTABLECIMIENTOS_RELACIONADOS_CON_NOMBRES_COMERCIALES = Seccion(112, "Cambios de Establecimientos Relacionados con Nombres Comerciales", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_TEQUILA = Seccion(401, "Autorización de Uso de La Denominación de Origen Tequila", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_MEZCAL = Seccion(402, "Autorización de Uso de La Denominación de Origen Mezcal", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_BACANORA = Seccion(404, "Autorización de Uso de La Denominación de Origen Bacanora", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_CAFE_VERACRUZ = Seccion(405, "Autorización de Uso de La Denominación de Origen Cafe Veracruz", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_AMBAR_DE_CHIAPAS = Seccion(406, "Autorización de Uso de La Denominación de Origen Ambar de Chiapas", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_TALAVERA = Seccion(407, "Autorización de Uso de La Denominación de Origen Talavera", Gaceta.CONSERVACION_DE_LOS_DERECHOS)
PROMOCIONES_DE_PATENTES_RELACIONADAS_CON_INVENCIONES_QUE_NO_SON_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS = Seccion(100224, "Promociones de patentes relacionadas con invenciones que no son susceptibles de ser empleadas en medicamentos alopáticos", Gaceta.PATENTES_VIGENTES_QUE_INCUMPLEN_LO_DISPUESTO_EN_EL_ART_162_LFPPI)
PROMOCIONES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_LA_MATERIA_INDICADA_EN_LA_PETICION_RESPECTIVA = Seccion(100227, "Promociones relacionadas a patentes que no protegen la materia indicada en la petición respectiva", Gaceta.PATENTES_VIGENTES_QUE_INCUMPLEN_LO_DISPUESTO_EN_EL_ART_162_LFPPI)
SOLICITUDES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_UN_MEDICAMENTO_ALOPATICO = Seccion(100622, "Solicitudes relacionadas a patentes que no protegen un medicamento alopático", Gaceta.PATENTES_VIGENTES_QUE_INCUMPLEN_LO_DISPUESTO_EN_EL_ART_162_LFPPI)
SOLICITUDES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_LA_MATERIA_INDICADA_EN_LA_PETICION_RESPECTIVA = Seccion(100624, "Solicitudes relacionadas a patentes que no protegen la materia indicada en la petición respectiva", Gaceta.PATENTES_VIGENTES_QUE_INCUMPLEN_LO_DISPUESTO_EN_EL_ART_162_LFPPI)
NOTIFICACIONES_DE_MARCAS = Seccion(100248, "Notificaciones de Marcas", Gaceta.NOTIFICACION_DE_RESOLUCIONES_REQUERIMIENTOS_Y_DEMAS_ACTOS)
NOTIFICACIONES_DE_AVISOS_COMERCIALES = Seccion(100250, "Notificaciones de Avisos Comerciales", Gaceta.NOTIFICACION_DE_RESOLUCIONES_REQUERIMIENTOS_Y_DEMAS_ACTOS)
NOTIFICACIONES_DE_NOMBRES_COMERCIALES = Seccion(100252, "Notificaciones de Nombres Comerciales", Gaceta.NOTIFICACION_DE_RESOLUCIONES_REQUERIMIENTOS_Y_DEMAS_ACTOS)
SOLICITUDES_DE_PATENTES = Seccion(100288, "Solicitudes de Patentes", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
SOLICITUDES_DE_REGISTROS_DE_MODELOS_DE_UTILIDAD = Seccion(100289, "Solicitudes de Registros de Modelos de Utilidad", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
SOLICITUDES_DE_REGISTROS_DE_DISENOS_INDUSTRIALES = Seccion(100290, "Solicitudes de Registros de Diseños Industriales", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
PATENTES_100293 = Seccion(100293, "Patentes", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
REGISTROS_DE_MODELOS_DE_UTILIDAD_100294 = Seccion(100294, "Registros de Modelos de Utilidad", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
REGISTROS_DE_DISENOS_INDUSTRIALES = Seccion(100295, "Registros de Diseños Industriales", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
REGISTROS_DE_ESQUEMAS_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS = Seccion(100296, "Registros de Esquemas de Trazado de Circuitos Integrados", Gaceta.NOTIFICACIONES_DE_LA_DIRECCION_DIVISIONAL_DE_PATENTES)
MODELOS_Y_DIBUJOS = Seccion(100310, "MODELOS Y DIBUJOS", Gaceta.RENOVACIONES_DE_DISENOS_INDUSTRIALES)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PROCESOS_DE_PROPIEDAD_INDUSTRIAL_100336 = Seccion(100336, "Emitidas por la Subdirección Divisional de Procesos de Propiedad Industrial", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_CUMPLIMIENTO_DE_EJECUTORIA_100337 = Seccion(100337, "Emitidas por la Subdirección Divisional de Cumplimiento de Ejecutoria", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_INFRACCIONES_ADMINISTRATIVAS_EN_MATERIA_DE_COMERCIO_100338 = Seccion(100338, "Emitidas por la Subdirección Divisional de Infracciones Administrativas en Materia de Comercio", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PREVENCION_DE_LA_COMPETENCIA_DESLEAL_100339 = Seccion(100339, "Emitidas por la Subdirección Divisional de Prevención de la Competencia Desleal", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)
RECURSOS_DE_REVISION_100340 = Seccion(100340, "Recursos de Revisión", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)
EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_MARCAS_NOTORIAS_INVESTIGACION_CONTROL_Y_PROCESAMIENTO_DE_DOCUMENTOS = Seccion(100342, "Emitidas por la Subdirección Divisional de Marcas Notorias; Investigación; Control y Procesamiento de Documentos", Gaceta.PUBLICACION_DE_ACUERDOS_DIARIAMENTE)


class Operador(Enum):
    AND = "AND"
    OR = "OR"
    NOT = "NOT"
    EMPTY = ""


class Kind(Enum):
    VALOR = "valor"   # term goes in datos[].valor
    FECHA = "fecha"   # term goes in datos[].fecha  (name starts with "Fecha")


@dataclass(frozen=True)
class Columna:
    nombre: str       # exact string the API expects in datos[].columna
    kind: Kind        # which datos field the search term belongs in


# COLUMNAS = {
  # 96 distinct columnas (GetDatosBySeccion). kind derived from the name.
ACTO = Columna("Acto", Kind.VALOR)
ACTOR = Columna("Actor", Kind.VALOR)
AGENTE = Columna("Agente", Kind.VALOR)
AGENTE_NACIONAL = Columna("Agente Nacional", Kind.VALOR)
ANUALIDADES = Columna("Anualidades", Kind.VALOR)
APODERADO = Columna("Apoderado", Kind.VALOR)
AUTORIZACION = Columna("Autorización", Kind.VALOR)
CATEGORIA = Columna("Categoría", Kind.VALOR)
CATEGORIA_DE_PROTECCION = Columna("Categoría de protección ", Kind.VALOR)
CLASE = Columna("Clase", Kind.VALOR)
CLASE_S = Columna("Clase (s)", Kind.VALOR)
CLASIFICACION_CIP = Columna("Clasificación CIP", Kind.VALOR)
CLASIFICACION_CPC = Columna("Clasificación CPC", Kind.VALOR)
DATOS_DEL_TITULAR = Columna("Datos del Titular", Kind.VALOR)
DEBE_DECIR = Columna("Debe decir", Kind.VALOR)
DEMANDADO = Columna("Demandado", Kind.VALOR)
DENOMINACION = Columna("Denominación", Kind.VALOR)
DENOMINACION_GENERICA = Columna("Denominación Genérica", Kind.VALOR)
DENOMINACION_GENERICA_O_NOMBRE_RECONOCIDO_INTERNACIONALMENTE = Columna("Denominación Genérica o Nombre Reconocido Internacionalmente", Kind.VALOR)
DENOMINACION_O_TITULO_DE_LA_INVENCION = Columna("Denominación o Título de la Invención", Kind.VALOR)
DESCRIPCION_ESPECIFICA = Columna("Descripción específica", Kind.VALOR)
DICE = Columna("Dice", Kind.VALOR)
DICTAMEN = Columna("Dictamen", Kind.VALOR)
ERROR_CORREGIDO = Columna("Error Corregido", Kind.VALOR)
ERROR_CORREGIDO_2 = Columna("Error corregido", Kind.VALOR)
EXPEDIENTE = Columna("Expediente", Kind.VALOR)
FECHA_DE_BOLETIN = Columna("Fecha de Boletín", Kind.FECHA)
FECHA_DE_CONCESION = Columna("Fecha de Concesión", Kind.FECHA)
FECHA_DE_PRESENTACION = Columna("Fecha de Presentación", Kind.FECHA)
FECHA_DE_PUBLICACION = Columna("Fecha de Publicación", Kind.FECHA)
FECHA_DE_PUESTA_EN_CIRCULACION = Columna("Fecha de Puesta en Circulación", Kind.FECHA)
FECHA_DE_REGISTRO_INTERNACIONAL = Columna("Fecha de Registro Internacional", Kind.FECHA)
FECHA_DE_CONCESION_2 = Columna("Fecha de concesión", Kind.FECHA)
FECHA_DE_LA_SOLICITUD_PRIORITARIA = Columna("Fecha de la solicitud Prioritaria", Kind.FECHA)
FECHA_DE_PETICION = Columna("Fecha de petición", Kind.FECHA)
FECHA_DE_PRESENTACION_2 = Columna("Fecha de presentación", Kind.FECHA)
FECHA_DE_PRESENTACION_INTERNACIONAL = Columna("Fecha de presentación internacional", Kind.FECHA)
FECHA_DE_PUBLICACION_INTERNACIONAL = Columna("Fecha de publicación internacional", Kind.FECHA)
FECHA_DE_RESOLUCION = Columna("Fecha de resolución", Kind.FECHA)
FICHA_PUBLICADA = Columna("Ficha Publicada", Kind.VALOR)
FOLIO_SALIDA = Columna("Folio/Salida", Kind.VALOR)
GACETA = Columna("Gaceta", Kind.VALOR)
INVENTOR_ES = Columna("Inventor(es)", Kind.VALOR)
LICENCIAS = Columna("Licencias", Kind.VALOR)
LICENCIATARIO = Columna("Licenciatario", Kind.VALOR)
LOCARNO = Columna("Locarno", Kind.VALOR)
MANDATO_JUDICIAL = Columna("Mandato Judicial", Kind.VALOR)
NACIONALIDAD_INVENTOR = Columna("Nacionalidad inventor", Kind.VALOR)
NO_RESOLUCION = Columna("No. Resolucion", Kind.VALOR)
NO_DE_REGISTRO = Columna("No. de Registro", Kind.VALOR)
NOMBRE_DE_INVENTOR_ES = Columna("Nombre de Inventor(es)", Kind.VALOR)
NOMBRE_DE_SOLICITANTE_S = Columna("Nombre de solicitante(s)", Kind.VALOR)
NOMBRE_GENERICO = Columna("Nombre genérico", Kind.VALOR)
NOMBRE_QUIMICO = Columna("Nombre químico", Kind.VALOR)
NUEVA_UBICACION = Columna("Nueva Ubicación", Kind.VALOR)
NUEVO_TITULAR = Columna("Nuevo Titular", Kind.VALOR)
NUMERO_DE_REGISTRO_INTERNACIONAL = Columna("Número de Registro Internacional", Kind.VALOR)
NUMERO_DE_CONCESION = Columna("Número de concesión", Kind.VALOR)
NUMERO_DE_EXPEDIENTE = Columna("Número de expediente", Kind.VALOR)
NUMERO_DE_PUBLICACION_INTERNACIONAL = Columna("Número de publicación internacional", Kind.VALOR)
NUMERO_DE_SOLICITUD = Columna("Número de solicitud", Kind.VALOR)
NUMERO_DE_SOLICITUD_INTERNACIONAL = Columna("Número de solicitud internacional", Kind.VALOR)
NUMERO_DEL_OFICIO = Columna("Número del Oficio", Kind.VALOR)
OBSERVACIONES = Columna("Observaciones", Kind.VALOR)
OFICINA_QUE_ATRIBUYE_LA_PRIORIDAD = Columna("Oficina que atribuye la Prioridad", Kind.VALOR)
OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO = Columna("Oficina, No de Patente y Tipo de documento", Kind.VALOR)
PATENTE = Columna("Patente", Kind.VALOR)
PETICION = Columna("Petición", Kind.VALOR)
PRIORIDAD_ES = Columna("Prioridad (es)", Kind.VALOR)
PRODUCTOS_Y_SERVICIOS = Columna("Productos y Servicios", Kind.VALOR)
PROMOCION = Columna("Promoción", Kind.VALOR)
RECURRENTE = Columna("Recurrente", Kind.VALOR)
REGISTRO_INTERNACIONAL = Columna("Registro Internacional", Kind.VALOR)
REGISTRO_DE_AVISO_COMERCIAL = Columna("Registro de Aviso Comercial", Kind.VALOR)
REGISTRO_DE_MARCA = Columna("Registro de Marca", Kind.VALOR)
REGISTRO_DE_MARCA_INTERNACIONAL = Columna("Registro de Marca Internacional", Kind.VALOR)
REGISTRO_DE_NOMBRE_COMERCIAL = Columna("Registro de Nombre Comercial", Kind.VALOR)
REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL = Columna("Registros Nacionales relacionados al Registro Internacional", Kind.VALOR)
REIVINDICACIONES = Columna("Reivindicaciones", Kind.VALOR)
RENOVADA_HASTA = Columna("Renovada Hasta", Kind.VALOR)
RESOLUCION = Columna("Resolución", Kind.VALOR)
RESUMEN = Columna("Resumen", Kind.VALOR)
SENTIDO = Columna("Sentido", Kind.VALOR)
SERIE_DEL_EXPEDIENTE = Columna("Serie del expediente", Kind.VALOR)
SET = Columna("Set", Kind.VALOR)
SITUACION_JURIDICA = Columna("Situación Jurídica", Kind.VALOR)
SOLICITANTE_S = Columna("Solicitante(s)", Kind.VALOR)
SUBLICENCIAS = Columna("Sublicencias", Kind.VALOR)
SUBLICENCIATARIO = Columna("Sublicenciatario", Kind.VALOR)
TIPO_DE_PATENTE = Columna("Tipo de Patente", Kind.VALOR)
TIPO_DE_DOCUMENTO = Columna("Tipo de documento", Kind.VALOR)
TITULAR = Columna("Titular", Kind.VALOR)
TITULAR_ES = Columna("Titular(es)", Kind.VALOR)
TITULO = Columna("Título", Kind.VALOR)
USUARIO_AUTORIZADO = Columna("Usuario Autorizado", Kind.VALOR)
VIGENCIA = Columna("Vigencia", Kind.VALOR)
# }


# Junction: which columnas are valid for each seccion (the 1035 pairs).
# Regenerate from columnas_snapshot.json.
SECCION_COLUMNAS: dict[Seccion, list[Columna]] = {
    MARCAS_REGISTRADAS: [CLASE, DATOS_DEL_TITULAR, DENOMINACION, EXPEDIENTE, FECHA_DE_CONCESION, FECHA_DE_PRESENTACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_MARCA],
    AVISOS_COMERCIALES_REGISTRADOS: [CLASE, DATOS_DEL_TITULAR, DENOMINACION, EXPEDIENTE, FECHA_DE_CONCESION, FECHA_DE_PRESENTACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_AVISO_COMERCIAL],
    NOMBRES_COMERCIALES_PUBLICADOS: [CLASE, DATOS_DEL_TITULAR, DENOMINACION, EXPEDIENTE, FECHA_DE_CONCESION, FECHA_DE_PRESENTACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_NOMBRE_COMERCIAL],
    FE_DE_ERRATAS_DE_MARCAS_REGISTRADAS_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    FE_DE_ERRATAS_DE_LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_MARCAS_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    FE_DE_ERRATAS_DE_AVISOS_COMERCIALES_REGISTRADOS_EN_EL_MES_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    FE_DE_ERRATAS_DE_RENOVACION_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    FE_DE_ERRATAS_DE_INSCRIPCION_DE_LIMITACION_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    FE_DE_ERRATAS_DE_INSCRIPCION_DE_CANCELACION_PARCIAL_GACETA_DE_JULIO_DEL_2016: [DEBE_DECIR, DICE, ERROR_CORREGIDO],
    SOLICITUDES_DE_PATENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_PATENTE_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_PATENTE_PUBLICADAS_ANTICIPADAMENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES_PUBLICADAS_ANTICIPADAMENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, PRIORIDAD_ES, RESUMEN, SOLICITANTE_S, TITULO],
    SOLICITUDES_QUE_SE_TRANSFORMARON_DE_REGISTROS_A_SOLICITUDES_DE_PATENTES: [AGENTE, CLASIFICACION_CIP, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DE_PATENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DE_PATENTE_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_NORMALES_PUBLICADAS_ANTICIPADAMENTE: [AGENTE, CLASIFICACION_CIP, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SOLICITANTE_S, TITULO],
    SOLICITUDES_DIVISIONALES_DE_PATENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD_CONFORME_AL_TRATADO_DE_COOPERACION_EN_MATERIA_DE_PATENTES: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DIVISIONALES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DE_MODELO_DE_UTILIDAD: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, ERROR_CORREGIDO_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL: [AGENTE, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_DIVISIONALES: [AGENTE, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DISENO_INDUSTRIAL: [AGENTE, ERROR_CORREGIDO_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_CONFORME_AL_SISTEMA_DE_LA_HAYA: [AGENTE, FECHA_DE_BOLETIN, FECHA_DE_PRESENTACION_2, FECHA_DE_REGISTRO_INTERNACIONAL, INVENTOR_ES, LOCARNO, NUMERO_DE_REGISTRO_INTERNACIONAL, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULAR_ES, TITULO],
    SOLICITUDES_DIVISIONALES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_CONFORME_AL_SISTEMA_DE_LA_HAYA: [AGENTE, FECHA_DE_BOLETIN, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULAR_ES, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DIVISIONALES_DE_PATENTE: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, ERROR_CORREGIDO_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, SET, SOLICITANTE_S, TITULO],
    FE_DE_ERRATAS_DE_SOLICITUDES_DE_REGISTRO_DE_DISENO_INDUSTRIAL_DIVISIONALES: [AGENTE, ERROR_CORREGIDO_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, SOLICITANTE_S, TITULO],
    PATENTES_302: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, SET, TITULAR, TITULO],
    REGISTROS_DE_MODELOS_DE_UTILIDAD_304: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, SET, TITULAR, TITULO],
    REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES_305: [AGENTE, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PUBLICACION, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    ESQUEMAS_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS: [AGENTE, CLASIFICACION_CIP, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    FE_DE_ERRATAS_DE_PATENTES: [AGENTE, CLASIFICACION_CIP, CLASIFICACION_CPC, ERROR_CORREGIDO_2, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, LOCARNO, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, SET, TITULAR, TITULO],
    FE_DE_ERRATAS_DE_REGISTROS_DE_MODELOS_DE_UTILIDAD: [AGENTE, CLASIFICACION_CIP, ERROR_CORREGIDO_2, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PRESENTACION_INTERNACIONAL, FECHA_DE_PUBLICACION, FECHA_DE_PUBLICACION_INTERNACIONAL, INVENTOR_ES, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    FE_DE_ERRATAS_DE_REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES: [AGENTE, ERROR_CORREGIDO_2, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PUBLICACION, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    FE_DE_ERRATAS_DE_LICENCIAS: [NUEVO_TITULAR, NUMERO_DE_CONCESION],
    REGISTROS_DE_MODELO: [FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, LOCARNO, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    CERTIFICADOS_DE_INVENCION: [CLASIFICACION_CIP, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    EMBARGOS_JUDICIALES_RELACIONADOS_CON_PATENTES: [FECHA_DE_PRESENTACION_2, NUMERO_DE_CONCESION],
    PATENTES_QUE_CUMPLIERON_SU_PLAZO_DE_VIGENCIA: [CLASIFICACION_CIP, FECHA_DE_LA_SOLICITUD_PRIORITARIA, NUMERO_DE_CONCESION, TITULAR, TITULO],
    ADHESION_DE_GOBIERNOS_A_LA_CONVENCION_DE_UNION_DE_PARIS: [NUMERO_DE_CONCESION],
    ADJUDICACION_DE_PATENTES_OTORGADAS: [NO_RESOLUCION, NUMERO_DE_CONCESION],
    PATENTES_CUYA_FALTA_DE_EXPLOTACION_SE_HA_COMPROBADO: [NUMERO_DE_CONCESION, TITULAR, TITULO],
    RESOLUCIONES_DE_PRIORIDAD_RELACIONADAS_CON_PATENTES_CONCEDIDAS: [NUMERO_DE_CONCESION],
    RECTIFICACIONES: [NUMERO_DE_CONCESION],
    INVENCIONES_CUYA_NOVEDAD_FUE_EXAMINADA: [FECHA_DE_PRESENTACION_2, NO_RESOLUCION, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULAR, TITULO],
    HIPOTECAS_SOBRE_DERECHOS_DE_PATENTES_CONCEDIDAS: [FECHA_DE_PRESENTACION_2, NUEVO_TITULAR, NUMERO_DE_CONCESION, TITULAR, TITULO],
    PATENTES_CUYA_PRIORIDAD_DE_FECHA_LEGAL_HA_SIDO_RECONOCIDA_EN_MEXICO: [FECHA_DE_LA_SOLICITUD_PRIORITARIA, NO_RESOLUCION, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, OFICINA_QUE_ATRIBUYE_LA_PRIORIDAD, TITULAR, TITULO],
    PATENTES_CUYOS_DERECHOS_DEL_SEGUNDO_PLAZO_FUERON_PAGADOS: [FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_CONCESION, TITULO],
    AVISOS_BIMESTRALES_EN_RELACION_CON_LA_EXPLOTACION_INDUSTRIAL_DE_PATENTES: [NUMERO_DE_CONCESION],
    PATENTES_QUE_HAN_SIDO_CONVERTIDAS_EN_DEFINITIVAS: [INVENTOR_ES, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULO],
    PATENTES_PROVISIONALES_QUE_HAN_CADUCADO_POR_NO_HABER_PAGADO_EL_IMPUESTO_DEL_SEGUNDO_PLAZO: [FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULO],
    ASUNTOS_ABANDONADOS_Y_DESECHADOS: [FECHA_DE_PRESENTACION_2, INVENTOR_ES, NUMERO_DE_CONCESION, TITULO],
    REGISTROS_DE_DISENOS_INDUSTRIALES_MODELOS_Y_DIBUJOS_INDUSTRIALES_100267: [AGENTE, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PUBLICACION, INVENTOR_ES, LOCARNO, NUMERO_DE_SOLICITUD, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    REGISTROS_DE_DISENOS_INDUSTRIALES_CONFORME_AL_ARREGLO_DE_LA_HAYA_MODELOS_Y_DIBUJOS_INDUSTRIALES: [AGENTE_NACIONAL, FECHA_DE_CONCESION_2, FECHA_DE_PRESENTACION_2, FECHA_DE_PUBLICACION, INVENTOR_ES, LOCARNO, NUMERO_DE_REGISTRO_INTERNACIONAL, NUMERO_DE_SOLICITUD, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, PRIORIDAD_ES, RESUMEN, TITULAR, TITULO],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PROCESOS_DE_PROPIEDAD_INDUSTRIAL_152: [ACTO, ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA, SENTIDO],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_CUMPLIMIENTO_DE_EJECUTORIA_153: [ACTO, ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA, RECURRENTE, SENTIDO],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_INFRACCIONES_ADMINISTRATIVAS_EN_MATERIA_DE_COMERCIO_154: [ACTO, ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA, SENTIDO],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PREVENCION_DE_LA_COMPETENCIA_DESLEAL_155: [ACTO, ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA, SENTIDO],
    RECURSOS_DE_REVISION_157: [ACTO, EXPEDIENTE, FOLIO_SALIDA, RECURRENTE, SENTIDO],
    TRANSMISION_DE_DERECHOS: [NUEVO_TITULAR, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD],
    LICENCIAS_DE_EXPLOTACION: [LICENCIATARIO, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD],
    SUBLICENCIAS_DE_EXPLOTACION: [NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, SUBLICENCIATARIO],
    TRANSFORMACION_DE_REGIMEN_JURIDICO: [NUEVO_TITULAR, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD],
    CAMBIO_DE_RAZON_SOCIAL: [NUEVO_TITULAR, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD],
    CAMBIOS_EN_PATENTES: [FECHA_DE_RESOLUCION, NO_RESOLUCION, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULAR],
    CAMBIOS_DE_REGISTROS_DE_DISENOS_INDUSTRIALES: [FECHA_DE_RESOLUCION, NO_RESOLUCION, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULAR],
    CAMBIOS_DE_REGISTROS_DE_MODELO_DE_UTILIDAD: [FECHA_DE_RESOLUCION, NO_RESOLUCION, NUMERO_DE_CONCESION, NUMERO_DE_SOLICITUD, TITULAR],
    PATENTES_VIGENTES_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS: [ANUALIDADES, DESCRIPCION_ESPECIFICA, NOMBRE_GENERICO, NOMBRE_QUIMICO, NUMERO_DE_CONCESION, OBSERVACIONES, REIVINDICACIONES, TITULAR, VIGENCIA],
    FE_DE_ERRATAS_100266: [ANUALIDADES, CATEGORIA_DE_PROTECCION, DENOMINACION_GENERICA_O_NOMBRE_RECONOCIDO_INTERNACIONALMENTE, DESCRIPCION_ESPECIFICA, LICENCIAS, NOMBRE_QUIMICO, OBSERVACIONES, PATENTE, REIVINDICACIONES, SUBLICENCIAS, TITULAR, VIGENCIA],
    LISTADO_DE_MEDICAMENTOS_VIGENTES: [ANUALIDADES, DESCRIPCION_ESPECIFICA, NOMBRE_GENERICO, NOMBRE_QUIMICO, NUMERO_DE_CONCESION, OBSERVACIONES, REIVINDICACIONES, TIPO_DE_PATENTE, TITULAR, VIGENCIA],
    PRIMERA_SECCION_FARMACOQUIMICOS: [ANUALIDADES, CATEGORIA_DE_PROTECCION, DENOMINACION_GENERICA_O_NOMBRE_RECONOCIDO_INTERNACIONALMENTE, DENOMINACION_O_TITULO_DE_LA_INVENCION, DESCRIPCION_ESPECIFICA, LICENCIAS, MANDATO_JUDICIAL, NOMBRE_QUIMICO, OBSERVACIONES, PATENTE, REIVINDICACIONES, SITUACION_JURIDICA, SUBLICENCIAS, TITULAR, VIGENCIA],
    SEGUNDA_SECCION_BIOTECNOLOGICOS: [ANUALIDADES, CATEGORIA_DE_PROTECCION, DENOMINACION_GENERICA_O_NOMBRE_RECONOCIDO_INTERNACIONALMENTE, DENOMINACION_O_TITULO_DE_LA_INVENCION, DESCRIPCION_ESPECIFICA, LICENCIAS, MANDATO_JUDICIAL, NOMBRE_QUIMICO, OBSERVACIONES, PATENTE, REIVINDICACIONES, SITUACION_JURIDICA, SUBLICENCIAS, TITULAR, VIGENCIA],
    SOLICITUDES_DE_MARCAS_ABANDONADAS: [DENOMINACION, EXPEDIENTE],
    SOLICITUDES_DE_NOMBRES_COMERCIALES_ABANDONADAS: [DENOMINACION, EXPEDIENTE],
    SOLICITUDES_DE_AVISOS_COMERCIALES_ABANDONADAS: [DENOMINACION, EXPEDIENTE],
    OFICIOS_REFERENTES_A_SOLICITUDES_DE_PATENTE: [AGENTE, NUMERO_DE_SOLICITUD, NUMERO_DEL_OFICIO, SOLICITANTE_S],
    OFICIOS_REFERENTES_A_SOLICITUDES_DE_DISENOS_INDUSTRIALES_O_MODELOS_DE_UTILIDAD: [AGENTE, NUMERO_DE_SOLICITUD, NUMERO_DEL_OFICIO, SOLICITANTE_S],
    SOLICITUDES_DE_PATENTE_ABANDONADAS_POR_FALTA_DE_PAGO_PARA_EXPEDICION_DE_TITULO: [FECHA_DE_PRESENTACION_2, NUMERO_DE_SOLICITUD, TITULAR],
    SOLICITUDES_DE_MODELOS_DE_UTILIDAD_ABANDONADAS_Y_DESISTIDAS: [FECHA_DE_PRESENTACION_2, NUMERO_DE_EXPEDIENTE, NUMERO_DE_SOLICITUD, SERIE_DEL_EXPEDIENTE, TITULAR],
    SOLICITUDES_DE_DISENOS_INDUSTRIALES_ABANDONADAS_Y_DESISTIDAS: [FECHA_DE_PRESENTACION_2, NUMERO_DE_EXPEDIENTE, NUMERO_DE_SOLICITUD, SERIE_DEL_EXPEDIENTE, TITULAR],
    CERTIFICADOS_DE_INVENCION_REGISTRADOS_DECLARADOS_CADUCOS_POR_TERMINO_DE_TIEMPO_DE_VIGENCIA: [INVENTOR_ES, NUMERO_DE_CONCESION, NUMERO_DE_EXPEDIENTE, NUMERO_DE_SOLICITUD, SERIE_DEL_EXPEDIENTE, TITULAR, TITULO],
    SOLICITUDES_DE_PATENTE_ABANDONADAS: [FECHA_DE_PRESENTACION_2, INVENTOR_ES, NACIONALIDAD_INVENTOR, NOMBRE_DE_INVENTOR_ES, NOMBRE_DE_SOLICITANTE_S, NUMERO_DE_CONCESION, NUMERO_DE_EXPEDIENTE, NUMERO_DE_SOLICITUD, RESUMEN, SERIE_DEL_EXPEDIENTE, TITULO],
    PATENTES_DECLARADAS_CADUCAS_POR_TERMINO_DE_SUS_PLAZOS_DE_VIGENCIA: [FECHA_DE_CONCESION_2, INVENTOR_ES, NUMERO_DE_CONCESION, TITULO],
    REGISTROS_DE_MODELO_Y_DIBUJOS_INDUSTRIALES_QUE_CADUCARON: [INVENTOR_ES, NUMERO_DE_CONCESION, TITULO],
    SOLICITUDES_DE_CERTIFICADOS_DE_INVENCION_ABANDONADOS: [NUMERO_DE_EXPEDIENTE],
    SOLICITUDES_DE_REGISTROS_DE_MODELO_ABANDONADOS: [NUMERO_DE_EXPEDIENTE],
    CITA_A_PAGO_DE_SOLICITUDES_DE_PATENTES: [AGENTE, NUMERO_DE_SOLICITUD, NUMERO_DEL_OFICIO, SOLICITANTE_S],
    CITA_A_PAGO_DE_SOLICITUDES_DE_MODELOS_DE_UTILIDAD: [AGENTE, NUMERO_DE_SOLICITUD, NUMERO_DEL_OFICIO, SOLICITANTE_S],
    SOLICITUDES_DE_USO_LIBRE_ABANDONADAS_DESISTIDAS_DESECHADAS_RETIRADAS_O_NEGADA_SU_CONCESION: [CLASIFICACION_CIP, CLASIFICACION_CPC, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, RESUMEN, SET, SOLICITANTE_S, TITULO],
    SOLICITUDES_DE_PATENTE_INTERNACIONALES_CUYA_FASE_NACIONAL_SE_ABANDONO_DESISTIO_DESECHO_O_RETIRO: [CLASIFICACION_CIP, CLASIFICACION_CPC, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD_INTERNACIONAL, RESUMEN, SET, SOLICITANTE_S, TITULO],
    PATENTES_CADUCAS_POR_TERMINO_DE_VIGENCIA: [CLASIFICACION_CIP, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    PATENTES_CADUCAS_POR_FALTA_DE_PAGO: [CLASIFICACION_CIP, CLASIFICACION_CPC, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, SET, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_MODELO_DE_UTILIDAD_CADUCOS_POR_TERMINO_DE_VIGENCIA: [CLASIFICACION_CIP, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_MODELO_DE_UTILIDAD_CADUCOS_POR_FALTA_DE_PAGO: [CLASIFICACION_CIP, CLASIFICACION_CPC, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, SET, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_DISENO_INDUSTRIAL_CADUCOS_POR_TERMINO_DE_VIGENCIA: [LOCARNO, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_DISENO_INDUSTRIAL_CADUCOS_POR_FALTA_DE_PAGO: [LOCARNO, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_ESQUEMA_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS_CADUCOS_POR_TERMINO_DE_VIGENCIA: [CLASIFICACION_CIP, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    REGISTROS_DE_ESQUEMA_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS_CADUCOS_POR_FALTA_DE_PAGO: [CLASIFICACION_CIP, NUMERO_DE_PUBLICACION_INTERNACIONAL, NUMERO_DE_SOLICITUD_INTERNACIONAL, OFICINA_NO_DE_PATENTE_Y_TIPO_DE_DOCUMENTO, RESUMEN, TIPO_DE_DOCUMENTO, TITULAR, TITULO],
    FE_DE_ERRATAS_10030: [ERROR_CORREGIDO_2, FECHA_DE_PUESTA_EN_CIRCULACION, FICHA_PUBLICADA, GACETA],
    SOLICITUDES_DE_MARCAS_11010: [DENOMINACION, EXPEDIENTE],
    SOLICITUDES_DE_NOMBRES_COMERCIALES_11020: [DENOMINACION, EXPEDIENTE],
    SOLICITUDES_DE_AVISOS_COMERCIALES_11030: [DENOMINACION, EXPEDIENTE],
    REGISTROS_DE_MARCAS: [DENOMINACION, REGISTRO_DE_MARCA],
    ORDENES_DE_PUBLICACION_DE_NOMBRES_COMERCIALES: [DENOMINACION, REGISTRO_DE_NOMBRE_COMERCIAL],
    REGISTROS_DE_AVISOS_COMERCIALES: [DENOMINACION, REGISTRO_DE_AVISO_COMERCIAL],
    SOLICITUDES_DE_MARCAS_100177: [DENOMINACION, EXPEDIENTE, REGISTRO_DE_MARCA],
    SOLICITUDES_DE_NOMBRES_COMERCIALES_100179: [DENOMINACION, EXPEDIENTE, REGISTRO_DE_NOMBRE_COMERCIAL],
    SOLICITUDES_DE_AVISOS_COMERCIALES_100181: [DENOMINACION, EXPEDIENTE, REGISTRO_DE_AVISO_COMERCIAL],
    SOLICITUDES_DE_INSCRIPCION_DE_LICENCIA_DE_USO_O_FRANQUICIA: [DENOMINACION, EXPEDIENTE],
    SOLICITUDES_DE_MARCAS_100188: [CLASE, DENOMINACION, EXPEDIENTE, FECHA_DE_PRESENTACION],
    SOLICITUDES_DE_AVISOS_COMERCIALES_100190: [CLASE, DENOMINACION, EXPEDIENTE, FECHA_DE_PRESENTACION],
    SOLICITUDES_DE_NOMBRES_COMERCIALES_100192: [CLASE, DENOMINACION, EXPEDIENTE, FECHA_DE_PRESENTACION],
    ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_AVISOS_COMERCIALES: [EXPEDIENTE, FECHA_DE_PRESENTACION],
    ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_MARCAS: [EXPEDIENTE, FECHA_DE_PRESENTACION],
    ESCRITOS_DE_OPOSICIONES_A_SOLICITUDES_DE_NOMBRES_COMERCIALES: [EXPEDIENTE, FECHA_DE_PRESENTACION],
    MARCAS_RENOVADAS_EN_EL_MES: [CLASE, DENOMINACION, REGISTRO_DE_MARCA, RESOLUCION],
    PERMISO_DE_USO_AUTORIZADO_DE_MARCAS: [DENOMINACION, LICENCIATARIO, REGISTRO_DE_MARCA, RESOLUCION],
    TRANSMISIONES_O_ENAJENACIONES_DE_DERECHOS_DE_MARCAS: [DENOMINACION, REGISTRO_DE_MARCA, RESOLUCION, TITULAR],
    CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_MARCAS: [DENOMINACION, NUEVO_TITULAR, REGISTRO_DE_MARCA, RESOLUCION],
    CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_MARCAS: [DENOMINACION, NUEVO_TITULAR, REGISTRO_DE_MARCA],
    CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_MARCAS: [APODERADO, DENOMINACION, REGISTRO_DE_MARCA, TITULAR],
    LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_MARCAS: [CLASE, DENOMINACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_MARCA, TITULAR],
    CAMBIOS_DE_UBICACION_DE_FABRICAS_O_ESTABLECIMIENTOS_RELACIONADOS_CON_MARCAS: [DENOMINACION, NUEVA_UBICACION, REGISTRO_DE_MARCA, RESOLUCION],
    NUEVA_UBICACION_DE_FABRICAS_SUBSIDIARIAS: [DENOMINACION, NUEVA_UBICACION, REGISTRO_DE_MARCA, RESOLUCION],
    INSCRIPCION_DE_CAMBIO_EN_EL_NOMBRE_DEL_TITULAR: [DENOMINACION, REGISTRO_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, RESOLUCION, TITULAR],
    INSCRIPCION_DE_UN_CAMBIO_EN_LA_TITULARIDAD_TOTAL: [DENOMINACION, REGISTRO_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, RESOLUCION, TITULAR],
    INSCRIPCION_DE_UN_CAMBIO_EN_LA_TITULARIDAD_PARCIAL: [CLASE_S, DENOMINACION, REGISTRO_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, RESOLUCION, TITULAR],
    RENOVACION: [CLASE_S, DENOMINACION, REGISTRO_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, RENOVADA_HASTA, RESOLUCION],
    INSCRIPCION_DE_LIMITACION: [CLASE_S, DENOMINACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_MARCA_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, TITULAR],
    INSCRIPCION_DE_CANCELACION_TOTAL: [DENOMINACION, REGISTRO_DE_MARCA_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, TITULAR],
    INSCRIPCION_DE_CANCELACION_PARCIAL: [CLASE_S, DENOMINACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_MARCA_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, TITULAR],
    RENUNCIA_REGISTROS_INTERNACIONALES: [DENOMINACION, REGISTRO_DE_MARCA_INTERNACIONAL, REGISTROS_NACIONALES_RELACIONADOS_AL_REGISTRO_INTERNACIONAL, TITULAR],
    AVISOS_COMERCIALES_RENOVADOS_EN_EL_MES: [DENOMINACION, REGISTRO_DE_AVISO_COMERCIAL, RENOVADA_HASTA, RESOLUCION],
    PERMISO_DE_USO_AUTORIZADO_DE_AVISOS_COMERCIALES: [DENOMINACION, LICENCIATARIO, REGISTRO_DE_AVISO_COMERCIAL, RESOLUCION],
    TRANSMISIONES_O_ENAJENACIONES_DE_AVISOS_COMERCIALES: [DENOMINACION, REGISTRO_DE_AVISO_COMERCIAL, RESOLUCION, TITULAR],
    CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_AVISOS_COMERCIALES: [DENOMINACION, NUEVO_TITULAR, REGISTRO_DE_AVISO_COMERCIAL, RESOLUCION],
    CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_AVISOS_COMERCIALES: [DENOMINACION, REGISTRO_DE_AVISO_COMERCIAL, TITULAR],
    CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_AVISOS_COMERCIALES: [APODERADO, DENOMINACION, REGISTRO_DE_AVISO_COMERCIAL, TITULAR],
    LIMITACION_DE_PRODUCTOS_FAVORABLES_DE_AVISOS_COMERCIALES: [CLASE, DENOMINACION, PRODUCTOS_Y_SERVICIOS, REGISTRO_DE_AVISO_COMERCIAL, TITULAR],
    CAMBIOS_DE_ESTABLECIMIENTOS_RELACIONADOS_CON_AVISOS_COMERCIALES: [DENOMINACION, NUEVA_UBICACION, REGISTRO_DE_AVISO_COMERCIAL, RESOLUCION],
    NOMBRES_COMERCIALES_RENOVADOS_EN_EL_MES: [DENOMINACION, REGISTRO_DE_NOMBRE_COMERCIAL, RENOVADA_HASTA, RESOLUCION],
    PERMISO_DE_USO_AUTORIZADO_DE_NOMBRES_COMERCIALES: [DENOMINACION, LICENCIATARIO, REGISTRO_DE_NOMBRE_COMERCIAL, RESOLUCION],
    TRANSMISIONES_O_ENAJENACIONES_DE_NOMBRES_COMERCIALES: [DENOMINACION, REGISTRO_DE_NOMBRE_COMERCIAL, RESOLUCION, TITULAR],
    CAMBIOS_DE_NOMBRE_JURIDICO_DE_TITULARES_DE_NOMBRES_COMERCIALES: [DENOMINACION, NUEVO_TITULAR, REGISTRO_DE_NOMBRE_COMERCIAL, RESOLUCION],
    CAMBIOS_DE_REGIMEN_JURIDICO_DE_TITULARES_DE_NOMBRES_COMERCIALES: [DENOMINACION, REGISTRO_DE_NOMBRE_COMERCIAL, TITULAR],
    CANCELACION_VOLUNTARIA_DE_REGISTROS_DE_NOMBRES_COMERCIALES: [APODERADO, DENOMINACION, REGISTRO_DE_NOMBRE_COMERCIAL, TITULAR],
    CAMBIOS_DE_ESTABLECIMIENTOS_RELACIONADOS_CON_NOMBRES_COMERCIALES: [DENOMINACION, NUEVA_UBICACION, REGISTRO_DE_NOMBRE_COMERCIAL, RESOLUCION],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_TEQUILA: [AUTORIZACION, USUARIO_AUTORIZADO],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_MEZCAL: [AUTORIZACION, USUARIO_AUTORIZADO],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_BACANORA: [AUTORIZACION, USUARIO_AUTORIZADO],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_CAFE_VERACRUZ: [AUTORIZACION, USUARIO_AUTORIZADO],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_AMBAR_DE_CHIAPAS: [AUTORIZACION, USUARIO_AUTORIZADO],
    AUTORIZACION_DE_USO_DE_LA_DENOMINACION_DE_ORIGEN_TALAVERA: [AUTORIZACION, USUARIO_AUTORIZADO],
    PROMOCIONES_DE_PATENTES_RELACIONADAS_CON_INVENCIONES_QUE_NO_SON_SUSCEPTIBLES_DE_SER_EMPLEADAS_EN_MEDICAMENTOS_ALOPATICOS: [CATEGORIA, DENOMINACION_GENERICA, DICTAMEN, OBSERVACIONES, PATENTE, PETICION, PROMOCION, REIVINDICACIONES, SOLICITANTE_S, TITULAR_ES],
    PROMOCIONES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_LA_MATERIA_INDICADA_EN_LA_PETICION_RESPECTIVA: [CATEGORIA, DENOMINACION_GENERICA, DICTAMEN, OBSERVACIONES, PATENTE, PETICION, PROMOCION, REIVINDICACIONES, SOLICITANTE_S, TITULAR_ES],
    SOLICITUDES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_UN_MEDICAMENTO_ALOPATICO: [CATEGORIA, DENOMINACION_GENERICA, DICTAMEN, FECHA_DE_PETICION, NUMERO_DE_CONCESION, PETICION, REIVINDICACIONES, SOLICITANTE_S, TITULAR],
    SOLICITUDES_RELACIONADAS_A_PATENTES_QUE_NO_PROTEGEN_LA_MATERIA_INDICADA_EN_LA_PETICION_RESPECTIVA: [DENOMINACION_GENERICA, DICTAMEN, FECHA_DE_PETICION, NUMERO_DE_CONCESION, PETICION, REIVINDICACIONES, SOLICITANTE_S, TITULAR],
    NOTIFICACIONES_DE_MARCAS: [EXPEDIENTE, REGISTRO_DE_MARCA, SERIE_DEL_EXPEDIENTE],
    NOTIFICACIONES_DE_AVISOS_COMERCIALES: [EXPEDIENTE, REGISTRO_DE_AVISO_COMERCIAL, SERIE_DEL_EXPEDIENTE],
    NOTIFICACIONES_DE_NOMBRES_COMERCIALES: [EXPEDIENTE, REGISTRO_DE_NOMBRE_COMERCIAL, SERIE_DEL_EXPEDIENTE],
    SOLICITUDES_DE_PATENTES: [EXPEDIENTE, NUMERO_DEL_OFICIO],
    SOLICITUDES_DE_REGISTROS_DE_MODELOS_DE_UTILIDAD: [EXPEDIENTE, NUMERO_DEL_OFICIO],
    SOLICITUDES_DE_REGISTROS_DE_DISENOS_INDUSTRIALES: [EXPEDIENTE, NUMERO_DEL_OFICIO],
    PATENTES_100293: [EXPEDIENTE, NUMERO_DE_CONCESION, NUMERO_DEL_OFICIO],
    REGISTROS_DE_MODELOS_DE_UTILIDAD_100294: [EXPEDIENTE, NUMERO_DE_CONCESION, NUMERO_DEL_OFICIO],
    REGISTROS_DE_DISENOS_INDUSTRIALES: [EXPEDIENTE, NUMERO_DE_CONCESION, NUMERO_DEL_OFICIO],
    REGISTROS_DE_ESQUEMAS_DE_TRAZADO_DE_CIRCUITOS_INTEGRADOS: [EXPEDIENTE, NUMERO_DE_CONCESION, NUMERO_DEL_OFICIO],
    MODELOS_Y_DIBUJOS: [NO_DE_REGISTRO, TITULO],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PROCESOS_DE_PROPIEDAD_INDUSTRIAL_100336: [ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_CUMPLIMIENTO_DE_EJECUTORIA_100337: [ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_INFRACCIONES_ADMINISTRATIVAS_EN_MATERIA_DE_COMERCIO_100338: [ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_PREVENCION_DE_LA_COMPETENCIA_DESLEAL_100339: [ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA],
    RECURSOS_DE_REVISION_100340: [EXPEDIENTE, FOLIO_SALIDA, RECURRENTE],
    EMITIDAS_POR_LA_SUBDIRECCION_DIVISIONAL_DE_MARCAS_NOTORIAS_INVESTIGACION_CONTROL_Y_PROCESAMIENTO_DE_DOCUMENTOS: [ACTOR, DEMANDADO, EXPEDIENTE, FOLIO_SALIDA],
}


@dataclass
class Dato:
    operador: Operador
    columna: Columna
    valor: str
    fecha: str = ""
